// Bean Validation
//
// License: Apache License, Version 2.0
// See the license.txt file in the root directory or <http://www.apache.org/licenses/LICENSE-2.0>.
:chapNum: {counter:chapter}
:index: 0
:tIndex: 0
[[builtinconstraints]]

== Built-in Constraint definitions

The specification defines a small set of built-in constraints. Their usage is encouraged both in regular constraint declarations and as composing constraints. Using this set of constraints will enhance portability of your constraints across constraint-consuming frameworks relying on the metadata API (such as client side validation frameworks or database schema generation frameworks).

Built-in annotations are annotated with an empty [classname]`@Constraint` annotation to avoid any dependency between the specification API and a specific implementation. [tck-testable]#Each Bean Validation provider must recognize built-in constraint annotations as valid constraint definitions and provide compliant constraint implementations for each.# [tck-testable]#The built-in constraint validation implementation is having a lower priority than an XML mapping definition.# In other words [classname]`ConstraintValidator` implementations for built-in constraints can be overridden by using the XML mapping (see <<xml-mapping-constraintdefinition>>).

All built-in constraints are in the [classname]`javax.validation.constraints` package. Here is the list of constraints and their declaration.

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@Null constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/Null.java[lines=7..8;26..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@NotNull constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/NotNull.java[lines=7..8;26..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@AssertTrue constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/AssertTrue.java[lines=7..8;26..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@AssertFalse constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/AssertFalse.java[lines=7..8;26..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@Min constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/Min.java[lines=7..8;26..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@Max constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/Max.java[lines=7..8;26..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@DecimalMin constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/DecimalMin.java[lines=7..8;26..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@DecimalMax constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/DecimalMax.java[lines=7..8;26..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@Size constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/Size.java[lines=7..8;26..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@Digits constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/Digits.java[lines=7..8;26..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@Past constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/Past.java[lines=7..8;29..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@Future constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/Future.java[lines=7..8;29..-1]
----

====

[caption="Example {chapter}.{counter:index}: "]

.[tck-testable]#@Pattern constraint#
====

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/constraints/Pattern.java[lines=7..8;26..-1]
----

====
