// Jakarta Bean Validation
//
// License: Apache License, Version 2.0
// See the license.txt file in the root directory or <http://www.apache.org/licenses/LICENSE-2.0>.

[[introduction]]

== Introduction

This document is the specification of the Java API for JavaBean validation in {spec-name-eeplatform} and Java SE. The technical objective of this work is to provide an object level constraint declaration and validation facility for the Java application developer, as well as a constraint metadata repository and query API.

It also offers method and constructor validation facilities to ensure constraints on their parameters and return values.

[[introduction-expertgroup]]
=== Expert group

This work has been conducted as part of the {spec-name-bv} under the link:https://jakarta.ee/about/jesp/[Jakarta EE Specification Process] and formerly JSR 380, 349 and 303 under the Java Community Process Program.
This specification is the result of the collaborative work of the members of the Expert Groups and the community at large.

The following persons have actively contributed to Bean Validation 2.0 as members of the JSR 380 expert group and the community at large in alphabetical order:

* Matt Benson
* Emmanuel Bernard (Red Hat, Inc.)
* Linda DeMichiel (Oracle)
* Hendrik Ebbers (Karakun AG)
* Hardy Ferentschik (Red Hat, Inc.)
* Christian Kaltepoth (ingenit GmbH & Co. KG)
* Werner Keil
* Marco Molteni (Genidea Sagl)
* Gunnar Morling (Red Hat, Inc.) - Specification Lead
* Michael Nascimento Santos
* Otavio Santana
* Guillaume Smet (Red Hat, Inc.)
* Tsuyoshi Yoshitomi (Fujitsu Limited)

The following persons have actively contributed to Bean Validation 1.1 as members of the JSR 349 expert group and the community at large in alphabetical order:

* Matt Benson
* Paul Benedict
* Emmanuel Bernard (Red Hat, Inc.) - Specification Lead
* Edward Burns (Oracle)
* Peter Davis
* Linda DeMichiel (Oracle)
* Hardy Ferentschik (Red Hat, Inc.)
* Antonio Goncalves
* Cemalettin Koç
* Rich Midwinter
* Gunnar Morling (individual then Red Hat, Inc.)
* Pete Muir (Red Hat, Inc.)
* Michael Nascimento Santos
* Gerhard Petracek
* Kevin Pollet (SERLI)
* Jagadish Prasath Ramu (Oracle)
* Bill Shannon (Oracle)
* Sebastian Thomschke


Former expert group members of JSR-303 in alphabetical order are:

* Geert Bevin
* Emmanuel Bernard (Red Hat, Inc.) - Specification Lead
* Uri Boness
* Erik Brakkee (Ericsson AB)
* Ed Burns (Sun Microsystems, Inc.)
* Jason Carreira
* Robert Clevenger (Oracle - retired)
* Linda DeMichiel (Sun Microsystems, Inc.)
* Tim Fennel
* Bharath Ganesh (Pramati Technologies)
* Romain Guy (Google Inc.)
* Robert Harrop
* Jacob J. Hookom
* Bob Lee (Google Inc.)
* Craig R. McClanahan (Sun Microsystems, Inc.)
* Niall K. Pemberton
* Steve Peterson
* Dhanji R. Prasanna (Google Inc., formerly individual)
* Gerhard Petracek
* Matt Raible
* Michael Nascimento Santos
* Sebastian Thomschke
* Jon Wetherbee (Oracle)

[[introduction-goals]]
=== Specification goals

Validating data is a common task that occurs throughout an application, from the presentation layer to the persistence layer. Often the same validation logic is implemented in each layer, proving to be time consuming and error-prone. To avoid duplication of these validations in each layer, developers often bundle validation logic directly into the domain model, cluttering domain classes with validation code that is, in fact, metadata about the class itself.

This specification defines a metadata model and API for JavaBean validation. The default metadata source is annotations, with the ability to override and extend the metadata through the use of XML validation descriptors.

The validation API developed by this specification is not intended for use in any one tier or programming model. It is specifically not tied to either the web tier or the persistence tier, and is available for both server-side application programming, as well as rich client Swing application developers. This API is seen as a general extension to the JavaBeans object model, and as such is expected to be used as a core component in other specifications. Ease of use and flexibility have influenced the design of this specification.

As of version 1.1, {spec-name-bv} constraints can also be applied to the parameters and return values of methods of arbitrary Java types. Thus the {spec-name-bv} API can be used to describe and validate the contract (comprising pre- and postconditions) applying to a given method ("Programming by Contract", PbC). Note that it is _not_ the goal of this specification to develop a fully-fledged PbC solution but rather an easy-to-use facility satisfying the most common needs related to applying constraints to method parameters and return values, based on the proven concepts of the {spec-name-bv} API.

[[introduction-requirements]]
=== Required Java version

The specification uses Java 8 language features. There is no requirement that implementations be compatible with Java language versions prior to 8.

[[introduction-documentorganization]]
=== How this document is organized

This document describes each aspect of the {spec-name-bv} specification in a separate chapter. One should remember that the specification is a consistent whole.

<<constraintsdefinitionimplementation>> describes how constraints are defined.

<<valueextractordefinition>> describes how extractors for the values of container types are defined.

<<constraintdeclarationvalidationprocess>> describes how a JavaBean class is decorated with annotations to describe constraints.

<<validationapi>> describes how to programmatically validate a JavaBean.

<<constraintmetadata>> describes how the metadata query API works.

<<builtinconstraints>> list all the built-in constraints.

<<xml>> describes the XML deployment descriptors for the configuration and the mapping.

<<exception>> describes the exception model and hierarchy used by {spec-name-bv}.

<<integration>> describes the different integration points of {spec-name-bv} with other technologies. In some cases one has to refer to the respective specifications for the up-to-date integration rules.

In <<terminology>>, key concepts are summarized. Some reviewers have found that reading the terminology section first helps to better understand the specification.

The changelog can be found at <<changelog>>.

[[introduction-commentingprocess]]
=== How to comment

The expert group is eager to receive feedback from readers. Feel free to contact us. You can get all the details at http://beanvalidation.org/contribute/.
