[[terminology]]


[appendix]
== Terminology

This appendix aims at giving an overview on the different key terms used through this specification. They are not to be considered formal definitions. Formal definitions are to be inferred from the core specification.

Constraint:: A restriction on a bean instance, the value of a field or the value of a JavaBean property.
Constraint declaration:: Assignment of a constraint to a target (bean, field, property) for a specific class. Typically by declaring an annotation on the target but can also be done through a XML deployment descriptor.
Validation routine:: Sequence of operations executed by the Bean Validation provider to validate a given object graph.
Constraint definition:: Defines a type of constraint, its attributes and the actual constraint validation implementations. Done through annotations. The list of constraint validation implementations can be provided via XML.
Group:: Constraints can belong to one or more group or context. Useful to apply a subset of the constraints for a given use case. By default, the `Default`  group is used.
Group Sequence:: Defines a group ordering in the validation process. If a given group in the sequence contains one or more failure, the following groups in the sequence must be ignored.
Constraint validation:: Constraint logic algorithm used to determine whether a given value passes a constraint or not.
Constraint validation implementation:: Class implementing the constraint logic and used to determine whether a given value pass a constraint or not.
Bean Validation provider:: Product implementing this specification.
Message interpolator:: Algorithm used to build the end user message associated to a constraint failure. Typically useful for i18n.
Constraint metadata API:: API exposing the constraints applied to a given bean type. Also considered one of the integration points with other JSR or frameworks.
Bootstrap API:: Bootstrapping part of the Bean Validation API producing a [classname]`ValidatorFactory`.
javax.validation.ConstraintValidator:: Interface implemented by a constraint validation implementation.
Composing constraint:: Constraint declared on another constraint definition. When the main constraint is validated, the composing constraints are validated too.
javax.validation.Validator:: Main API. Holds contracts to validate object graphs.
javax.validation.ConstraintViolation:: Interface describing a given constraint failure on a given bean.
Getter:: Method whose:
* name starts with `get` and has a return type but no parameter
* name starts with `is`, has no parameter and is returning [classname]`boolean`
