// Bean Validation
//
// License: Apache License, Version 2.0
// See the license.txt file in the root directory or <http://www.apache.org/licenses/LICENSE-2.0>.

[[valueextractordefinition]]
== Value extractor definition

Validation of container element constraints as well as cascaded validation of generic container types requires access to the values stored in the container.
The retrieval of values stored in a container is handled via implementations of the `ValueExtractor` interface:

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/valueextraction/ValueExtractor.java[lines=7..8;17..-1]
----

[tck-testable]#The validation engine passes the container instance and a value receiver object to the `extractValues()` method.#
[tck-testable]#The value extractor is only invoked if the container is not `null`.#
Value extractor implementations must invoke one of the `ValueReceiver` methods for each element contained in the container, passing the element value and, optionally, a node name.
When calling

* [tck-testable]#`value()`, the given value will be passed to the validation engine#;
* [tck-testable]#`iterableValue()`, the given value will be passed to the validation engine and the corresponding property path node (see <<validationapi-constraintviolation>>) will be marked as iterable, i.e. `Node#isInIterable()` returns `true`#;
* [tck-testable]#`indexedValue()`, the given value will be passed to the validation engine and the corresponding property path node will be marked as iterable and it will have set the given index, i.e. `Node#getIndex()` returns the given index value#;
* [tck-testable]#`keyedValue()`, the given value will be passed to the validation engine and the corresponding property path node will be marked as iterable and it will have set the given key, i.e. `Node#getKey()` returns the given key value#.

[tck-testable]#When passing a non-null node name to any of the receiver methods and when the extractor is called in the course of container element validation (not during cascaded validation),
a node of kind `CONTAINER_ELEMENT` will be appended to the property path, with `Node#getName()` returning the specified name.#
[tck-testable]#If null is passed as node name, no node will be appended to the property path.
The resulting property path will then be the same as if the constraint had been given on the container instead of a container element.
That is desirable for pure wrapper types such as `Optional`, `OptionalInt` etc.#

The container value passed to a value extractor is retrieved from the element that hosts the type argument carrying the constraint or `@Valid` annotation:

[source,java]
----
private Map<String, @Valid @RetailOrder Order> ordersByName;

public Map<@NotNull String, Order> getOrdersByName() {
    return ordersByName;
}
----

[tck-testable]#When validating the `@NotNull` constraint, the map as returned by the getter will be passed to the map key extractor in order to obtain the map keys.#
[tck-testable]#When validating the `@RetailOrder` constraint and performing cascaded validation,
the map as obtained directly from the field will be passed to the map value extractor in order to obtain the map values.#

[[valueextractordefinition-extractedvalue]]
=== @ExtractedValue

The `@ExtractedValue` annotation is used to denote the element extracted by a given value extractor:

[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/valueextraction/ExtractedValue.java[lines=7..8;16..-1]
----

[tck-testable]#The `@ExtractedValue` annotation must be specified exactly once for a value extractor type.#

For generic container types (e.g. `java.util.List`), `@ExtractedValue` is to be specified on a type argument of the container type as used in the extractor definition.
[tck-not-testable]#Only wildcard type arguments are supported as target for `@ExtractedValue` in this case.#

[NOTE]
====
This implies that only one extractor is supported for a given generic type.
I.e. there can be an extractor for `List<?>`, but not one for `List<String>` and one for `List<Integer>`.
====

[tck-testable]#For non-generic container types (e.g. `java.util.OptionalInt`), `@ExtractedValue` is to be specified on the container type as used in the extractor definition.
The type of the wrapped element(s) must be specified using `@ExtractedValue#type()` in this case.#

[tck-testable]#In case an illegal value extractor definition is detected, a `ValueExtractorDefinitionException` is raised.#

[[valueextractordefinition-unwrapbydefault]]
=== @UnwrapByDefault

Value extractor definitions can be marked with the `@UnwrapByDefault` annotation.
[tck-testable]#This causes constraints to be automatically applied to the wrapped value if a constraint is found for an element handled by that extractor# (see <<constraintdeclarationvalidationprocess-containerelementconstraints-implicitunwrapping>>):

.`@UnwrapByDefault` annotation
====
[source, JAVA, indent=0]
----
include::{validation-api-source-dir}javax/validation/valueextraction/UnwrapByDefault.java[lines=7..8;16..-1]
----
====

[[valueextractordefinition-builtinvalueextractors]]
=== Built-in value extractors

Compatible implementations provide value extractors for the following types out of the box:

* [tck-testable]#`java.util.Iterable`; `iterableValue()` must be invoked for each contained element, passing the string literal `<iterable element>` as node name#
* [tck-testable]#`java.util.List`; `indexedValue()` must be invoked for each contained element, passing the string literal `<list element>` as node name#
* [tck-testable]#`java.util.Map`; both map keys and map values are to be supported;
`keyedValue()` must be invoked by the map key extractor for each contained key, passing the string literal `<map key>` as node name;
`keyedValue()` must be invoked by the map value extractor for each contained value, passing the string literal `<map value>` as node name#
* [tck-testable]#`java.util.Optional`; `value()` must be invoked (passing the contained value or `null` if none is present), passing `null` as node name#
* [tck-testable]#`java.util.OptionalInt`, `java.util.OptionalLong` and `java.util.OptionalDouble`; the extracted value types must be `java.lang.Integer`, `java.lang.Long` and `java.lang.Double`, respectively. `value()` must be invoked (passing the contained value or `null` if none is present), passing `null` as node name. The extractors must be marked with `@UnwrapByDefault`.#

In environments where http://docs.oracle.com/javase/8/javafx/get-started-tutorial/jfx-overview.htm#JFXST784[JavaFX] is present, compatible implementations additionally provide extractors for the following types out of the box:

* [tck-testable]#`javafx.beans.observable.ObservableValue`; `value()` must be invoked with the observable value, passing `null` as node name; the extractor must be marked with `@UnwrapByDefault`#
* [tck-testable]#`javafx.beans.property.ReadOnlyListProperty` and `javafx.beans.property.ListProperty`; `indexedValue()` must be invoked for each contained element, passing the string literal `<list element>` as node name#
* [tck-testable]#`javafx.beans.property.ReadOnlySetProperty` and `javafx.beans.property.SetProperty`; `iterableValue()` must be invoked for each contained element, passing the string literal `<iterable element>` as node name#
* [tck-testable]#`javafx.beans.property.ReadOnlyMapProperty` and `javafx.beans.property.MapProperty`; both map keys and map values are to be supported;
`keyedValue()` must be invoked by the map key extractor for each contained key, passing the string literal `<map key>` as node name;
`keyedValue()` must be invoked by the map value extractor for each contained value, passing the string literal `<map value>` as node name#

Additional value extractors (amending or overriding the set of built-in extractors) can be registered when bootstrapping the validation engine (see <<constraintdeclarationvalidationprocess-validationroutine-valueextractorresolution-registering>>).

[[valueextractordefinition-examples]]
=== Examples

A value extractor for the elements of `java.util.List`:

[source,java]
----
class ListValueExtractor implements ValueExtractor<List<@ExtractedValue ?>> {

	@Override
	public void extractValues(List<?> originalValue, ValueReceiver receiver) {
		for ( int i = 0; i < originalValue.size(); i++ ) {
			receiver.indexedValue( "<list element>", i, originalValue.get( i ) );
		}
	}
}
----

This extractor passes each element contained in the given list to the receiver object,
using the literal `<list element>` as a node name.

A value extractor for `java.util.Optional`:

[source,java]
----
public class OptionalValueExtractor implements ValueExtractor<Optional<@ExtractedValue ?>> {

	@Override
	public void extractValues(Optional<?> originalValue, ValueExtractor.ValueReceiver receiver) {
		receiver.value( null, originalValue.orElse( null ) );
	}
}
----

This extractor passes the element wrapped by the given `Optional` to the receiver object, if present.
`null` is passed as a node name, causing no node to be appended to the resulting property path.
I.e. when the constraint the `@Size` constraint in `private Optional<@Size(min=1) String name;` is violated,
the resulting property path will be the same as if a constraint hosted on the `name` field itself was violated.

A value extractor for `java.util.OptionalInt`:

[source,java]
----
@UnwrapByDefault
public class OptionalIntValueExtractor implements ValueExtractor<@ExtractedValue(type = Integer.class) OptionalInt> {

	@Override
	public void extractValues(OptionalInt originalValue, ValueReceiver receiver) {
		receiver.value( null, originalValue.isPresent() ? originalValue.getAsInt() : null );
	}
}
----

This extractor passes the `int` value wrapped by the given `OptionalInt` to the receiver object, if present.
`null` is passed as a node name, causing no node to be appended to the resulting property path.
As the extractor is marked with `@UnwrapByDefault`,
any constraint declared on an element of type `OptionalInt` will implicitly be applied to the wrapped `int` value instead of the `OptionalInt` itself.

[tck-testable]#The following extractor definition is illegal as it specifies `@ExtractedValue` more than once:#

[source,java]
----
public class IllegalMapExtractor implements ValueExtractor<Map<@ExtractedValue ?, @ExtractedValue ?>> { ... }
----

[tck-not-testable]#The following extractor definition is unsupported as it specifies `@ExtractedValue` on a non-wildcard type argument:#

[source,java]
----
public class StringListValueExtractor implements ValueExtractor<List<@ExtractedValue String>> { ... }
----
