// Jakarta Bean Validation
//
// License: Apache License, Version 2.0
// See the license.txt file in the root directory or <http://www.apache.org/licenses/LICENSE-2.0>.

[[whatsnew]]

== What's new

[NOTE]
====
Names used under the JCP for specifications are preserved in the What's new section for versions released prior to the move to Jakarta EE in order to preserve historical accuracy.
====

[[whatsnew-30]]
=== What's new in 3.0

The only changes in Bean Validation 3.0 are changes to support the Jarkarta EE javax to jakarta package namespace change.

The changes include:

* All `javax.validation.*` packages have moved to `jakarta.validation.*`.
* The namespace for Bean Validation XML descriptors has been changed to `\https://jakarta.ee/xml/ns/validation/configuration` for `META-INF/validation.xml` and `\https://jakarta.ee/xml/ns/validation/mapping` for constraint mapping files (see <<validationapi-bootstrapping-xmlconfiguration>>)

[[whatsnew-20]]
=== What's new in 2.0

The main contribution of Bean Validation 2.0 is leveraging the new language features and API additions of Java 8 for the purposes of validation.
Java 8 or later is required to use Bean Validation 2.0.

The changes include:

* Support for validating container elements by annotating type arguments of parameterized types, e.g. `List<@Positive Integer> positiveNumbers` (see <<constraintdeclarationvalidationprocess-containerelementconstraints>>);
this also includes:
** More flexible cascaded validation of collection types; e.g. values _and_ keys of maps can be validated now: `Map<@Valid CustomerType, @Valid Customer> customersByType`
** Support for `java.util.Optional`
** Support for the property types declared by JavaFX
** Support for custom container types by plugging in additional value extractors (see <<valueextractordefinition>>)
* Support for the new date/time data types for `@Past` and `@Future` (see <<builtinconstraints>>);
fine-grained control over the current time and time zone used for validation (see <<constraintsdefinitionimplementation-validationimplementation-temporalvalidators>>)
* New built-in constraints: `@Email`, `@NotEmpty`, `@NotBlank`, `@Positive`, `@PositiveOrZero`, `@Negative`, `@NegativeOrZero`, `@PastOrPresent` and `@FutureOrPresent` (see <<builtinconstraints>>)
* All built-in constraints are marked as repeatable now
* Parameter names are retrieved using reflection (see <<constraintdeclarationvalidationprocess-methodlevelconstraints-parameterconstraints-namingparameters>>)
* `ConstraintValidator#initialize()` is a default method (see <<constraintsdefinitionimplementation-validationimplementation>>)
* The namespace for Bean Validation XML descriptors has been changed to `http://xmlns.jcp.org/xml/ns/validation/configuration` for `META-INF/validation.xml` and `http://xmlns.jcp.org/xml/ns/validation/mapping` for constraint mapping files (see <<validationapi-bootstrapping-xmlconfiguration>>)

[[whatsnew-11]]
=== What's new in 1.1

Bean Validation 1.1 improves and builds upon Bean Validation 1.0. The expert group and the community have been working on a few specific areas.

[[whatsnew-11-openness]]
==== Openness

All of Bean Validation 1.1 work has been done in the open and in an open source way. Source code for the API, reference implementation, test compatibility kit as well as the specification and the website sources are available in the open. All discussions are done in the open in the publicly available development mailing list. Road map and proposals are also published on the website.

You can find all the details (mailing lists, source repositories etc.) at http://beanvalidation.org.

[[whatsnew-11-dependencyinjection]]
==== Dependency injection

Bean Validation uses a few components [classname]`MessageInterpolator`, [classname]`TraversableResolver`, [classname]`ParameterNameProvider`, [classname]`ConstraintValidatorFactory` and [classname]`ConstraintValidator`. Bean Validation 1.1 standardizes how these objects are managed by a container and how these objects can benefit from container services. In particular, CDI support within Java EE is being defined.

[[whatsnew-11-methodvalidation]]
==== Method validation

Bean Validation 1.1 allows to put constraints to the parameters and return values of arbitrary methods and constructors. That way the Bean Validation API can be used to describe and validate the contract applying to a given method or constructor, that is:

* the preconditions that must be met by the caller before the method or constructor may be invoked and
* the postconditions that are guaranteed to the caller after a method or constructor invocation returns.


This enables a programming style known as "Programming by Contract" (PbC). Compared to traditional means of checking the sanity of argument and return values this approach has several advantages:

* These checks are expressed declaratively and don't have to be performed manually, which results in less code to write, read and maintain.
* The pre- and postconditions applying for a method or constructor don't have to be expressed again in the documentation, since any of its annotations will automatically be included in the generated JavaDoc. This reduces redundancies, thus avoiding efforts and inconsistencies between implementation and documentation.

[[whatsnew-11-contextdependencyinjection]]
==== Integration with CDI

The integration points with CDI have been increased and reworked. This opens up for a more natural and standard integration both in Java EE and Java SE and encompass dependency injection, component lifecycle management and interception for method validation.

[[whatsnew-11-groupconversion]]
==== Group conversion

The specification offers a way to alter the targeted group when validation cascading is happening. This feature is particularly useful to reuse a given object (graph) and to avoid leaking groups between various object subgraphs. It also makes for more readable constraints.

[[whatsnew-11-expressionlanguage]]
==== Message interpolation via the unified expression language

Constraint violation messages can now use EL expressions for a much more flexible rendering and string formatting. In particular a formatter object is injected in the EL context to convert numbers, dates etc. into the locale specific string representation. Likewise, the validated value is also available in the EL context.

[[whatsnew-11-others]]
==== Others

Many more minor changes have been done. Check out the change log for more details at <<changelog>>.
